name: Setup Node
description: Setup node, pnpm and install dependencies
inputs:
  pnpmVersion:
    description: The version of pnpm to install
    required: false
    default: 8.6.6
  nodeVersion:
    description: The version of NodeJs to install
    required: false
    default: 16.18.1
  githubToken:
    description: Github Token
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4.0.0
      with:
        version: ${{ inputs.pnpmVersion }}
        run_install: false
    - uses: actions/setup-node@v3.6.0
      env:
        GITHUB_TOKEN: ${{ inputs.githubToken }}
      with:
        node-version: ${{ inputs.nodeVersion }}
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml
    - run: pnpm install --ignore-scripts --frozen-lockfile
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.githubToken }}
