name: Create pull request on version change
on:
  workflow_call: 
    secrets:
      githubToken:
        description: Github Token
        required: true

jobs:
  create_pr:
    name: Create a version pull request if necessary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0
      - uses: cpdevtools/common-github-workflows/.github/actions/create-release-pull-request@main
        with:
          githubToken: ${{ secrets.githubToken }}
