name: Builds and save docker image artifacts
on:
  workflow_call: 
    inputs:
      projectName:
        description: the project name to build
        required: true
        type: string
jobs:
  build_and_run_tests:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Project
        uses: actions/checkout@v3.3.0
      
      - name: Install Node & Dependencies
        uses: cpdevtools/common-github-workflows/.github/actions/node-setup-pnpm@main
      
      - name: Run Build Script
        uses: cpdevtools/common-github-workflows/.github/actions/pnpm-run-recursive@main
        with:
          script: actions-build 
          projectFilter: ${{ inputs.projectName }}

      - name: Upload image
        uses: ishworkh/container-image-artifact-upload@v1.0.0
        with:
          image: "${{ inputs.projectName }}:latest"