on:
  workflow_call:

jobs:
  check_version_valid_and_new:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0

      - name: Check Version
        uses: ./.github/actions/check-version

      - name: Install Node & Dependencies
        uses: ./.github/actions/node-setup-pnpm