name: Builds and publish docker project
on:
  workflow_call: 
    inputs:
      projectName:
        description: the project name to build
        required: true
        type: string
      nodeVersion:
        description: "The version of NodeJs to install"
        required: false
        default: "v16.18.1"
        type: string
      githubToken:
        description: "Github Token"
        required: false
        default: ${{ github.token }}
        type: string
      githubActor:
        description: "Github Actor"
        required: false
        default: ${{ github.actor }}
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate release version
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0

      - name: Check Version
        uses: ./.github/actions/check-version

  build_and_publish:
    name: Build and publish to registy
    needs: [validate]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0
      
      - name: Install Node & Dependencies
        uses: ./.github/actions/node-setup-pnpm
      
      - name: Run Build Script
        uses: ./.github/actions/pnpm-run-recursive
        with:
          script: actions-build 
          projectFilter: ${{ inputs.projectName }}

      - name: Publish
        uses: ./.github/actions/publish-docker-image-pnpm
        with:
          image: ${{ inputs.projectName }}
          nodeVersion: ${{ inputs.nodeVersion }}

  create-release:
    name: Create github release and add version tags
    runs-on: ubuntu-latest
    needs: [build_and_publish]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0

      - name: Create Release
        uses: ./.github/actions/create-release
