name: Run Tests using pnpm
on:
  workflow_call:
    inputs:
      nodeVersion:
        description: The version of NodeJs to install
        required: false
        type: string
        default: v16.18.1
      toNpm:
        description: Publish to npm package registry
        type: boolean
        required: false
        default: false
      toGithub:
        description: Publish to github package registry
        required: false
        type: boolean
        default: true
    secrets:
      npmToken:
        description: NPM Token
        required: false
      githubToken:
        description: Github Token
        required: false
jobs:
  build_and_run_tests:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0
      - name: Install Node & Dependencies
        uses: cpdevtools/common-github-workflows/.github/actions/node-setup-pnpm@v0.0.18
        with:
          nodeVersion: ${{ inputs.nodeVersion }}
          githubToken: ${{ secrets.githubToken }}
      - name: Build
        uses: cpdevtools/common-github-workflows/.github/actions/run-build@v0.0.18
      - name: Set Version
        uses: cpdevtools/common-github-workflows/.github/actions/run-set-version@v0.0.18
      - name: Pack
        uses: cpdevtools/common-github-workflows/.github/actions/run-pack@v0.0.18
      - name: Publish
        uses: cpdevtools/common-github-workflows/.github/actions/publish-node-package-pnpm@v0.0.18
        with:
          nodeVersion: ${{ inputs.nodeVersion }}
          toNpm: ${{ inputs.toNpm }}
          toGithub: ${{ inputs.toGithub }}
          githubToken: ${{ secrets.githubToken }}
          npmToken: ${{ secrets.npmToken }}
      - name: Create Release
        uses: cpdevtools/common-github-workflows/.github/actions/create-release@v0.0.18
