name: Run Tests using pnpm
on:
  workflow_call:
    inputs:
      nodeVersion:
        description: The version of NodeJs to install
        required: false
        type: string
        default: v16.18.1
      toNpm:
        description: Publish to npm package registry
        type: boolean
        required: false
        default: false
      toGithub:
        description: Publish to github package registry
        required: false
        type: boolean
        default: true
    secrets:
      NPM_TOKEN:
        description: NPM Token
        required: false
      GITHUB_TOKEN:
        description: NPM Token
        required: false
jobs:
  build_and_run_tests:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0
      - name: Install Node & Dependencies
        uses: cpdevtools/common-github-workflows/.github/actions/node-setup-pnpm@main
        with:
          nodeVersion: ${{ inputs.nodeVersion }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: cpdevtools/common-github-workflows/.github/actions/run-build@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set Version
        uses: cpdevtools/common-github-workflows/.github/actions/run-set-version@main

      - name: Pack
        uses: cpdevtools/common-github-workflows/.github/actions/run-pack@main

      - name: Publish
        uses: cpdevtools/common-github-workflows/.github/actions/publish-node-package-pnpm@main
        with:
          nodeVersion: ${{ inputs.nodeVersion }}
          toNpm: ${{ inputs.toNpm }}
          toGithub: ${{ inputs.toGithub }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          npmToken: ${{ secrets.NPM_TOKEN }}
