name: Check Version
on:
  workflow_call: 

jobs:
  check_pr_version:
    name: Version is valid for release
    runs-on: ubuntu-latest
    steps:
      name: check version
      - uses: cpdevtools/common-github-workflows/.github/actions/check-version@main