name: Run Tests using pnpm
on:
  workflow_call: null
jobs:
  build_and_run_tests:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0
      - name: Install Node & Dependencies
        uses: cpdevtools/common-github-workflows/.github/actions/node-setup-yarn@v0.0.11
      - name: Build
        uses: cpdevtools/common-github-workflows/.github/actions/run-build@v0.0.11
        with:
          packageManager: yarn
      - name: Run Tests
        uses: cpdevtools/common-github-workflows/.github/actions/run-test@v0.0.11
        with:
          packageManager: yarn
